# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1heGm-DsId7bzzHtKMR61F5OagXzPvvyu
"""


import streamlit as st
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix
import io
from contextlib import redirect_stdout

st.title("Social Network Ads Purchase Prediction")

st.write("The purpose of this application is to predict whether a user will purchase a product based on their gender, age, and estimated salary.")
st.write("This application uses a Logistic Regression model trained on the `Social_Network_Ads.csv` dataset.")

st.write("---")
st.header("1. Data Loading and Overview")

# Load the dataset
st.title("Social Network Ads Data Analysis")

# File uploader
uploaded_file = st.file_uploader("Upload your CSV file", type="csv")

if uploaded_file:
    try:
        # Read the CSV into a DataFrame
        df = pd.read_csv(uploaded_file)
        st.success("File uploaded successfully!")
        st.write("Preview of your data:", df.head())
        
        # You can continue with your ML code here, e.g. train_test_split
        # from sklearn.model_selection import train_test_split
        # X = df[['Age', 'EstimatedSalary']]
        # y = df['Purchased']
        # X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)
        
    except Exception as e:
        st.error(f"Error reading CSV: {e}")
else:
    st.info("Please upload a CSV file to get started.")

st.subheader("Data Information")
# Capture df.info() output
f = io.StringIO()
with redirect_stdout(f):
    df.info()
info_output = f.getvalue()
st.text(info_output)

st.subheader("Descriptive Statistics for Numerical Features")
st.dataframe(df.describe())

st.subheader("Descriptive Statistics for Categorical Features")
st.dataframe(df.describe(include="object"))

st.subheader("Missing Values")
st.write(df.isnull().sum())

st.subheader("Duplicate Rows")
st.write(f"Number of duplicate rows: {df.duplicated().sum()}")

st.write("---")
st.header("2. Data Preprocessing and Model Training")

# Define input and output
ip = df[['Gender', 'Age', 'EstimatedSalary']]
op = df['Purchased']

st.subheader("Input Features (ip first 5 rows)")
st.dataframe(ip.head())

st.subheader("Target Variable (op first 5 rows)")
st.dataframe(op.head())

# Split data and one-hot encode the 'Gender' column
x_train, x_test, y_train, y_test = train_test_split(ip, op, random_state=20)
x_train = pd.get_dummies(x_train, drop_first=True)
x_test = pd.get_dummies(x_test, drop_first=True)

st.subheader("Processed Training Features (x_train first 5 rows)")
st.dataframe(x_train.head())

st.subheader("Processed Test Features (x_test first 5 rows)")
st.dataframe(x_test.head())

# Train the Logistic Regression model
model = LogisticRegression()
model.fit(x_train, y_train)
st.success("Logistic Regression Model Trained Successfully!")

st.write("---")
st.header("3. Model Evaluation")

# Make predictions
pred = model.predict(x_test)

st.subheader("Evaluation Metrics on Test Set")

accuracy = accuracy_score(y_test, pred)
st.metric(label="Accuracy Score", value=f"{accuracy:.4f}")

precision = precision_score(y_test, pred)
st.metric(label="Precision Score", value=f"{precision:.4f}")

recall = recall_score(y_test, pred)
st.metric(label="Recall Score", value=f"{recall:.4f}")

st.subheader("Confusion Matrix")
cm = confusion_matrix(y_test, pred)
st.dataframe(pd.DataFrame(cm,
             index=['Actual Not Purchased (0)', 'Actual Purchased (1)'],
             columns=['Predicted Not Purchased (0)', 'Predicted Purchased (1)']
             ))

st.write("---")
st.header("4. Make Predictions (Interactive Demo)")
st.write("Adjust the parameters below to see the prediction for a new user.")

# User inputs for prediction
with st.form("prediction_form"):
    gender = st.selectbox("Gender", ["Male", "Female"])
    age = st.slider("Age", 18, 60, 30)
    estimated_salary = st.slider("Estimated Salary", 15000, 150000, 70000)

    submitted = st.form_submit_button("Predict Purchase")

    if submitted:
        # Prepare input for prediction
        gender_male = 1 if gender == "Male" else 0
        new_data = pd.DataFrame([[age, estimated_salary, gender_male]],
                                columns=['Age', 'EstimatedSalary', 'Gender_Male'])

        st.subheader("Input for Prediction:")
        st.dataframe(new_data)

        # Predict
        new_prediction = model.predict(new_data)
        prediction_proba = model.predict_proba(new_data)

        st.subheader("Prediction Result")
        if new_prediction[0] == 1:
            st.success("This user is predicted to **Purchase** the product!")
        else:
            st.error("This user is predicted **Not to Purchase** the product.")

        st.write(f"Probability of Not Purchasing: {prediction_proba[0][0]:.4f}")
        st.write(f"Probability of Purchasing: {prediction_proba[0][1]:.4f}")

st.write("---")
st.info("To run this Streamlit app:\n1. Save the code above to a Python file (e.g., `app.py`).\n2. Open your terminal or command prompt.\n3. Navigate to the directory where you saved `app.py`.\n4. Run the command: `streamlit run app.py`\n   (Make sure you have Streamlit installed: `pip install streamlit`)")
